### PR TITLE
Add a few unit test cases for MoveIt!

### PR DESCRIPTION
**Pull request by 130s**

### CODE REVIEW

**Comment by 130s** [comment]
Now travis passed with all the tests run.

Note that initially I added these tests into `vs060` package. But found out that `vs060` doesn't depend on `vs060_moveit_config` that the test uses.  Then since `denso_launch` pkg already depends on vs060_moveit_config, I moved the tests into there.

**Comment by k-okada** [comment]
can we catch https://github.com/start-jsk/denso/issues/62 problem with this pr?

**Comment by 130s** [comment]
> can we catch #62 problem with this pr?

These tests DO catch something, but I'm not sure if the something is equal to #62.

I repeatedly tested the following 2 cases:
- With the #64, which is a patch to #62, test passes.
  
  ```
  $ rostest denso_launch vs060.test 
  :
  [ROSTEST]-----------------------------------------------------------------------
  
  [denso_launch.rosunit-test_move_group/test_hz][passed]
  [denso_launch.rosunit-test_moveit_py/test_list_activejoints][passed]
  [denso_launch.rosunit-test_moveit_py/test_list_movegroups][passed]
  [denso_launch.rosunit-test_moveit_py/test_plan][passed]
  [denso_launch.rosunit-test_moveit_py/test_planandexecute][passed]
  
  SUMMARY
  * RESULT: SUCCESS
  * TESTS: 5
  * ERRORS: 0
  * FAILURES: 0
  ```
- If I remove the patch #64, test fails:
  
  ```
  [ROSTEST]-----------------------------------------------------------------------
  
  [denso_launch.rosunit-test_move_group/test_hz][FAILURE]-------------------------
  no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
  --------------------------------------------------------------------------------
  
  
  SUMMARY
  * RESULT: FAIL
  * TESTS: 1
  * ERRORS: 1
  * FAILURES: 1
  ```

So this error is happening at `hztest` of a topic `/move_group/status` (https://github.com/start-jsk/denso/pull/65/files#diff-c659d96ef2f1b43ea4f67461720aa391R11), which I have no idea why; the patch #64 is in denso controller, which is at lower lever than MoveIt! so that #64 shouldn't affect MoveIt! topics. In fact when I observed #62 without this unit tests, some output from MoveIt! processes were printed (see [the output](https://github.com/start-jsk/denso/issues/62#issue-114925887)). 

Maybe the issue at controller-level prevented MoveIt! from publishing `/move_group/status` topic?

**Comment by 130s** [comment]
Confirmed #62 is caught; without the patch, looks like controller manager cannot be started (pr2_controller_manager) and thus controller related tests fail.

I think it's good to merge this.

Used https://github.com/130s/denso/commit/f456c7666bb3c8a918bd24ed2897189fa933c1b5

```
$ rostest denso_launch vs060.test
:
[ INFO] [1447002252.339744467]: waitForService: Service [/pr2_controller_manager/list_controllers] could not connect to host [tork-kudu1:51116], waiting...
[ INFO] [1447002257.344279741]: Waiting for service pr2_controller_manager/list_controllers to come up
[ INFO] [1447002257.345403943]: waitForService: Service [/pr2_controller_manager/list_controllers] could not connect to host [tork-kudu1:51116], waiting...
[ INFO] [1447002262.355138771]: Waiting for service pr2_controller_manager/list_controllers to come up
[ INFO] [1447002262.356748859]: waitForService: Service [/pr2_controller_manager/list_controllers] could not connect to host [tork-kudu1:51116], waiting...
[ INFO] [1447002267.371725220]: Waiting for service pr2_controller_manager/list_controllers to come up
[ INFO] [1447002267.372418385]: waitForService: Service [/pr2_controller_manager/list_controllers] could not connect to host [tork-kudu1:51116], waiting...
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 161, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 92, in main
    rospy.wait_for_service('pr2_controller_manager/load_controller')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...

All is well! Everyone is happy! You can start planning now!

[ WARN] [1447002272.775174502]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
mlockall: Cannot allocate memory
[ WARN] [1447002272.789669454]: server: 133.11.216.51:5007
[ WARN] [1447002272.790405366]: udp_timeout: 9000 micro sec
[ WARN] [1447002272.796017453]: min_acceptable_rt_loop_frequency changed to 100.000000
[ INFO] [1447002272.796666676]: realtime loop period is 8000000.000000
[ INFO] [1447002272.797339789]: pidfile is: open_controller.pid
[ INFO] [1447002272.798361466]: piddir is: /var/tmp/run/
[ INFO] [1447002272.892436080]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1447002272.892684623]: No root joint specified. Assuming fixed joint
[ INFO] [1447002272.970616199]: success to initialize the controller manager
main: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = OpenControllersInterface::ControllerStatus; typename boost::detail::sp_member_access<T>::type = OpenControllersInterface::ControllerStatus*]: Assertion `px != 0' failed.
[ INFO] [1447002273.299513661]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1447002273.299554956]: No root joint specified. Assuming fixed joint
[ WARN] [1447002273.570361129]: The root link BASE has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1447002273.575161611]: Loading robot model 'vs060A1_AV6_NNN_NNN'...
[ INFO] [1447002273.575197524]: No root joint specified. Assuming fixed joint
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 161, in <module>
    if __name__ == '__main__': main()
  File "/opt/ros/indigo/lib/pr2_controller_manager/spawner", line 92, in main
    rospy.wait_for_service('pr2_controller_manager/load_controller')
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 159, in wait_for_service
    raise ROSInterruptException("rospy shutdown")
rospy.exceptions.ROSInterruptException: rospy shutdown
Starting context monitors...
Context monitors started.
testtest_move_group ... ok
testtest_moveit_py ... ok

[ROSTEST WARNINGS]--------------------------------------------------------------

 * [/home/rospasta/cws_industrial/src/start-jsk/denso/denso_launch/launch/denso_vs060_startup_skelton.launch] unknown <node> attribute 'gdb-launch-prefix'

[ROSTEST]-----------------------------------------------------------------------

[denso_launch.rosunit-test_move_group/test_hz][FAILURE]-------------------------
no messages before timeout
  File "/usr/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 117, in test_hz
    self._test_hz(hz, hzerror, topic, test_duration, wait_time)
  File "/opt/ros/indigo/share/rostest/nodes/hztest/hztest", line 152, in _test_hz
    self.assert_(self.message_received, "no messages before timeout")
  File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 0
 * FAILURES: 1

rostest log file is in /home/rospasta/.ros/log/rostest-tork-kudu1-29693.log
```

Error message of these tests don't clearly tell where the root cause is, because these are tests for MoveIt!. We need to add tests in the controller level in order to capture the specific errors about #62.

**Comment by k-okada** [comment]
nice, double checked in #66

**Comment by k-okada** [comment]
even though travis said OK, but  if we look the travis log closer, this patch is also fails as follows (https://travis-ci.org/start-jsk/denso/jobs/90002585), hope https://github.com/k-okada/denso/commit/5ab6eaf6c704023bc01d0585c49e6fe42d58563f catches

```
testdenso_vs060_moveit_demo_test ... ok
[ROSTEST WARNINGS]--------------------------------------------------------------
 * [/home/travis/catkin_ws/src/denso/denso_launch/launch/denso_vs060_startup_skelton.launch] unknown <node> attribute 'gdb-launch-prefix'
[ROSTEST]-----------------------------------------------------------------------
[denso_launch.rosunit-denso_vs060_moveit_demo_test/test_moveit][ERROR]----------
Unable to connect to move_group action server within allotted time (2)
  File "/usr/lib/python2.7/unittest/case.py", line 322, in run
    self.setUp()
  File "/home/travis/catkin_ws/src/denso/denso_launch/test/denso_vs060_moveit_demo_test.py", line 14, in setUp
    self.arm = MoveGroupCommander("manipulator")
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 51, in __init__
    self._g = _moveit_move_group_interface.MoveGroup(name, "robot_description")
--------------------------------------------------------------------------------
SUMMARY
 * RESULT: FAIL
 * TESTS: 1
 * ERRORS: 1
 * FAILURES: 0
```

**Comment by k-okada** [comment]
create new PR to update travis check, this should fail if test did not pass https://github.com/start-jsk/denso/pull/67

I also noticed

```
  # Build tests                                                                 
  - catkin build --limit-status-rate 0.1 --no-notify --make-args tests
  # Run tests                                                                   
  - catkin run_tests
```

is really build and run tests, at the end of https://travis-ci.org/start-jsk/denso/jobs/90005843
we can see

```
[ROSTEST]-----------------------------------------------------------------------
[denso_launch.rosunit-denso_vs060_moveit_demo_test/test_moveit][ERROR]----------
Unable to connect to move_group action server within allotted time (2)
  File "/usr/lib/python2.7/unittest/case.py", line 322, in run
    self.setUp()
  File "/home/travis/catkin_ws/src/denso/denso_launch/test/denso_vs060_moveit_demo_test.py", line 14, in setUp
    self.arm = MoveGroupCommander("manipulator")
  File "/opt/ros/indigo/lib/python2.7/dist-packages/moveit_commander/move_group.py", line 51, in __init__
    self._g = _moveit_move_group_interface.MoveGroup(name, "robot_description")
--------------------------------------------------------------------------------
```

it uses test.py under src/denso, not installed software. I think this is not correct.

**Comment by 130s** [comment]
> even though travis said OK, but if we look the travis log closer, this patch is also fails as follows (https://travis-ci.org/start-jsk/denso/jobs/90002585), hope k-okada@5ab6eaf catches

Very thoughtful to catch this error. I still don't quite understand the [answer from Dirk in this thread], but looks like `catkin_test_results` works in the case like ours.

Looks like the updated tests are all green.

**Comment by 130s** [comment]
> even though travis said OK, but if we look the travis log closer, this patch is also fails as follows (https://travis-ci.org/start-jsk/denso/jobs/90002585), hope k-okada@5ab6eaf catches

Very thoughtful to catch this error. I still don't quite understand the [answer from Dirk in this thread](http://answers.ros.org/question/136951/how-to-specify-test-packge-in-catkin_make-test/), but looks like `catkin_test_results` works in the case like ours.

Looks like the updated tests are all green.

**Comment by 130s** [comment]
Please review and merge if this LGTY @k-okada @garaemon

**Comment by k-okada** [comment]
if travis said ok, it is ok.

## 

◉ Kei Okada

**Pull request merged**
