### PR TITLE
use ros_control

### PR DESCRIPTION
**Pull request by ompugao**
pr2_controllers and pr2_mechanism are not supported anymore and ros-control is recommended in kinetic.
we need to use ros-control and drop a dependency to pr2_* (and open_controllers_interface accordingly).

please 
- create kinetic-devel branch
- drop dependency of vs060 to open_controllers_interface

before you merge this pr.

*please do not merge this pr yet!*

### CODE REVIEW

**Comment by 130s** [comment]
@ompugao thank you for working on this!
All tests are failing https://travis-ci.org/start-jsk/denso/builds/197923073 Do you have any idea to fix them?

**Comment by ompugao** [comment]
fixed

**Comment by k-okada** [comment]
@ompugao I have created kinetic-branch , is this ok for you? https://github.com/start-jsk/denso/tree/kinetic-devel

**Comment by 130s** [comment]
FYI there's another? user who's trying this package on Kinetic. http://answers.ros.org/question/266755/install-denso-package-in-ros-kinetic/

**Pull request merged**
